### ISSUE TITLE
customBetaDiv For grid values

### ISSUE THREAD

**Issue by Tao-Liang** [ptitle/epm#7]
Hello Pascal,
 sorry, it is me again. May I ask you a question about customBetaDiv function, I plan to calculate the betadivaersity, I aslo interested in the environmental  factors (or others like, spRichness, altitude) differences (i.e. abs(diff(focal and neighboring)), ) between focal hexagons and its neighboring, and then calculate the mean or max values. How should I write the funtion, I have rastered the environmental factors and cbind these data into  tamiasEPM object ($grid$Factor1, Factor2, ....). It was not belong to dat or phylo object, so I confused how to write the function after vec[[i]]<-abs (diff(###)). Could you please give me some tips?
Here are my funtions (i plan to calculated the spRichness difference as a practice), but it was wrong.
FGridDifference<-function(cellList){
  vec <- numeric(length(cellList)) 
  for (i in 1:length(cellList)){ 
    vec[[i]]<-abs(diff(cellList[[i]]$spRichness))}
  return(mean(vec, na.rm = TRUE)) }

 Thanks in advance.

**Comment by ptitle** [comment]
Hi,

Apologies for the delay in responding. 

First, the reason your example isn't working is because you need to think of the input to your custom function (`FGridDifference`) as a list of taxon names. And you need to refer to `dat` as the trait vector or dataframe that will be subsetted with those taxon names. Since you wanted to calculate the difference in richness across neighbor groups, I did the following. See that for richness here, I just took the number of rows for `dat[cellList[[i]],]` because that will be the number of species for which there is trait data.

```
FGridDifference <- function(cellList) {
	vec <- numeric(length(cellList))
	for (i in 1:length(cellList)) {
		vec[[i]] <- nrow(dat[cellList[[i]],])
	}
	return(diff(range(vec, na.rm = TRUE)))
}

tamiasEPM <- addPhylo(tamiasEPM, tamiasTree)
tamiasEPM <- addTraits(tamiasEPM, tamiasTraits)

xx <- customBetaDiv(tamiasEPM, fun = FGridDifference, radius = 70000, minTaxCount = 2, metricName = 'richDiff')

```

But as for your main question, I think you are interested in calculating similar differences across cells and their neighbors, for a variety of datasets, including some that are not really species-specific, such as environmental rasters.

If that is what you would like to do, then I think this epm function is not the ideal way to go about this. You could, but you would be bending this function toward a purpose that it was not designed for. You would be better off writing your own for-loop. You can identify neighbors of cells a number of different ways. I use `spdep::dnearneigh`. 

I hope this helps!

**Comment by Tao-Liang** [comment]
I see, yes, I want to do the anlyses for the mean value of hexagon-hexagon environmental factors. Thank you so much~Title!

Good day










--

Best
Tao Liang
School of Zoology, Tel Aviv University, Israel. 




At 2024-05-20 21:44:29, "ptitle" ***@***.***> wrote:

Hi,

Apologies for the delay in responding.

First, the reason your example isn't working is because you need to think of the input to your custom function (FGridDifference) as a list of taxon names. And you need to refer to dat as the trait vector or dataframe that will be subsetted with those taxon names. Since you wanted to calculate the difference in richness across neighbor groups, I did the following. See that for richness here, I just took the number of rows for dat[cellList[[i]],] because that will be the number of species for which there is trait data.

FGridDifference <- function(cellList) {
	vec <- numeric(length(cellList))
	for (i in 1:length(cellList)) {
		vec[[i]] <- nrow(dat[cellList[[i]],])
	}
	return(diff(range(vec, na.rm = TRUE)))
}

tamiasEPM <- addPhylo(tamiasEPM, tamiasTree)
tamiasEPM <- addTraits(tamiasEPM, tamiasTraits)

xx <- customBetaDiv(tamiasEPM, fun = FGridDifference, radius = 70000, minTaxCount = 2, metricName = 'richDiff')



But as for your main question, I think you are interested in calculating similar differences across cells and their neighbors, for a variety of datasets, including some that are not really species-specific, such as environmental rasters.

If that is what you would like to do, then I think this epm function is not the ideal way to go about this. You could, but you would be bending this function toward a purpose that it was not designed for. You would be better off writing your own for-loop. You can identify neighbors of cells a number of different ways. I use spdep::dnearneigh.

I hope this helps!
